import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Define the font using localFont
const raleway = localFont({
  src: "./fonts/Raleway-VariableFont_wght.ttf",
  variable: "--font-raleway", // Optional: define a CSS variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} antialiased`} // Apply the className here
      >
        {children}
      </body>
    </html>
  );
}
